import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    fontSize: {
      'xs': ['.75rem', '1rem'],
      'sm': ['.875rem', '1.25rem'],
      'md': ['1rem', '1.5rem'],
      'lg': ['1.25rem', '1.75rem'],
      'xl': ['1.5rem', '2rem'],
    },
    screens: {
      'xl':  { 'max': '1600px'},
      'lg':  { 'max': '991px'},
      'md':  { 'max': '767px'},
      'sm':  { 'max': '478px'},
    },
    extend: {
      gridTemplateColumns: {
        '24': 'repeat(24, minmax(0, 1fr))',
      },
      gridColumnStart: {
        '14': '14',
        '15': '15',
        '16': '16',
        '17': '17',
        '18': '18',
        '19': '19',
        '20': '20',
        '21': '21',
        '22': '22',
        '23': '23',
        '24': '24',
        '25': '25',
      },
      gridColumnEnd: {
        '14': '14',
        '15': '15',
        '16': '16',
        '17': '17',
        '18': '18',
        '19': '19',
        '20': '20',
        '21': '21',
        '22': '22',
        '23': '23',
        '24': '24',
        '25': '25',
      },
      gridColumn: {
        'span-14': 'span 14 / span 14',
        'span-15': 'span 15 / span 15',
        'span-16': 'span 16 / span 16',
        'span-17': 'span 17 / span 17',
        'span-18': 'span 18 / span 18',
        'span-19': 'span 19 / span 19',
        'span-20': 'span 20 / span 20',
        'span-21': 'span 21 / span 21',
        'span-22': 'span 22 / span 22',
        'span-23': 'span 23 / span 23',
        'span-24': 'span 24 / span 24',
        'span-25': 'span 25 / span 25',
      },
      spacing: {
        'none': '0',
        '4xs': '.25rem',
        '3xs': '.5rem',
        '2xs': '.75rem',
        'xs': '1rem',
        'sm': '1.5rem',
        'md': '2rem',
        'lg': '3rem',
        'xl': '6rem',
        '2xl': '8rem',
        '3xl': '12rem',
        '4xl': '16rem',
        'col-sm': 'var(--col-sm)',
        'col-md': 'var(--col-md)',
        'col-lg': 'var(--col-lg)',
        'col-xl': 'var(--col-xl)',
        'col-2xl': 'var(--col-2xl)',
        'col-3xl': 'var(--col-3xl)',
        'col-4xl': 'var(--col-4xl)',
        'col-5xl': 'var(--col-5xl)',
        'col-6xl': 'var(--col-6xl)',
        'col-7xl': 'var(--col-7xl)',
        'col-8xl': 'var(--col-8xl)',
        'col-9xl': 'var(--col-9xl)',
        'side-xs': 'var(--side-xs)',
        'side-sm': 'var(--side-sm)',
        'side-md': 'var(--side-md)',
        'side-lg': 'var(--side-lg)',
        'side-xl': 'var(--side-xl)',
        'side-2xl': 'var(--side-2xl)',
        'side-3xl': 'var(--side-3xl)',
        'side-4xl': 'var(--side-4xl)',
        'side-5xl': 'var(--side-5xl)',
        'side-6xl': 'var(--side-6xl)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
  ],
  safelist: [
    { pattern: /^mt-/, variants: ["xl", "lg", "md", "sm"] },
    { pattern: /^mb-/, variants: ["xl", "lg", "md", "sm"] },
    { pattern: /^pt-/, variants: ["xl", "lg", "md", "sm"] },
    { pattern: /^pb-/, variants: ["xl", "lg", "md", "sm"] },
  ],
};
export default config;
